name: Deploy to Production

on:
  push:
    branches:
      - main  # Deploy to production on main branch merge

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.PRODUCTION_SERVER_IP }} \
          "cd /app && git pull origin main && systemctl restart app"
